### ISSUE TITLE
Update Hyperlinks on hfradar.ioos.us to the New Scripps CORDC HFRNet URL

### ISSUE THREAD

**Issue by Zelenke** [ioos/hfradar-dac-landing#25]
On https://hfradar.ioos.us/, update the hyperlink of the CORDC map image and the text "Scripps page" beneath to http://cordc.ucsd.edu/projects/mapping/maps/.  (Both those links point to the now defunct URL http://cordc.ucsd.edu/projects/mapping/maps/fullpage.php?).  Please confirm with @mwengren and brian.zelenke@noaa.gov once complete.

**Comment by MathewBiddle** [comment]
@Zelenke the link on https://hfradar.ioos.us/ now points to the correct site.
